language: node_js
node_js:
  - '8'
dist: trusty # needs Ubuntu Trusty
sudo: required
addons:
  chrome: stable # have Travis install chrome stable.

script:
  - npm install
  - npm run build
  - npm run test
